/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.AlumnoController;
import controlador.CursaController;
import controlador.DocentesController;
import controlador.MatriculaController;
import controlador.listas.ListaEnlazada;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Alumno;
import modelo.Cursa;
import modelo.Docente;
import modelo.Matricula;
import vista.Utilidades.Utilidades;

/**
 *Vista para poder asignar asistencia a un alumno especifico
 * @author TecnoeXtrem
 */
public class DialogAsignarAsistencia extends javax.swing.JDialog {

    private FondoPanel fondo = new FondoPanel();
    private DocentesController docenteControlador = new DocentesController();
    private MatriculaController matriculaControler = new MatriculaController();
    private CursaController cursaC = new CursaController();
    private AlumnoController alumnController = new AlumnoController();

    /**
     * Creates new form DialogAsignarAsistencia
     */
    public DialogAsignarAsistencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public DialogAsignarAsistencia(java.awt.Frame parent, boolean modal, Alumno alumno, Docente docente, Cursa cursa,
            ListaEnlazada<Matricula> matriculaList) {
        super(parent, modal);
        initComponents();
//        this.setContentPane(fondo);
        alumnController.setAlumno(alumno);
        docenteControlador.setDocente(docente);
        cursaC.setCursa(cursa);
        matriculaControler.setMatriculaList(matriculaList);
        obtenerHoraAsignatura();
        this.setLocationRelativeTo(this);
    }

    public void obtenerHoraAsignatura() {
        try {
            lblHorasMateria.setText(String.valueOf(cursaC.getCursa().getAsignatura().getNumeroHoras()));
        } catch (Exception e) {
            System.out.println("Errioe en obtner el numero de horas " + e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHorasMateria = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtHorasAsistidas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Asignar Asistencia");

        jLabel2.setText("Numero de horas de la materia: ");

        lblHorasMateria.setText("H");

        jLabel3.setText("Numero de horas asistidas: ");

        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorasMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHorasAsistidas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)
                        .addGap(72, 72, 72)
                        .addComponent(btnAsignar)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblHorasMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHorasAsistidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignar)
                    .addComponent(btnRegresar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmDocente diaDocente = new FrmDocente(null, true, docenteControlador.getDocente());
        this.setVisible(false);
        diaDocente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        asignarAsistencia();
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * Metodo para poder asignar la asistencia a un estudiante
     * Captura el numero de horas del estudiante y calcula el porcentaje usando el metodo de su controler
     */
    public void asignarAsistencia() {
        cursaC.getCursa().setHorasAsistidas(Integer.parseInt(txtHorasAsistidas.getText()));
        cursaC.calcularPorcentajeHorasAsistidas();
        System.out.println("Id estudiante  " + alumnController.getAlumno().getId());
        System.out.println("Nombre materia " + cursaC.getCursa().getAsignatura().getNombre());
        try {
            for (int i = 0; i < matriculaControler.getMatriculaList().getSize(); i++) {
                for (int j = 0; j < matriculaControler.getMatriculaList().obtener(i).getCursa().getSize(); j++) {
                    System.out.println("Materia " + matriculaControler.getMatriculaList().obtener(i).getCursa().obtener(j).getAsignatura().getNombre());
                    if (matriculaControler.getMatriculaList().obtener(i).getAlumno().getId() == alumnController.getAlumno().getId()
                            && matriculaControler.getMatriculaList().obtener(i).getCursa().obtener(j).getAsignatura().getNombre()
                            == cursaC.getCursa().getAsignatura().getNombre()) {
                        matriculaControler.getMatriculaList().obtener(i).getCursa().obtener(j).setHorasAsistidas(cursaC.getCursa().getHorasAsistidas());
                        matriculaControler.getMatriculaList().obtener(i).getCursa().obtener(j).setPorcentajeHorasAsistidas(cursaC.getCursa().getPorcentajeHorasAsistidas());
                        System.out.println("Porcentaje de sasistencia" + matriculaControler.getMatriculaList().obtener(i).getCursa().obtener(j).getPorcentajeHorasAsistidas());
                        System.out.println("Porcentaje de horas asistidas" + matriculaControler.getMatriculaList().obtener(i).getCursa().obtener(j).getHorasAsistidas());
                        Utilidades.modificarMatricula(matriculaControler.getMatriculaList().obtener(i), (matriculaControler.getMatriculaList().obtener(i).getIdMatricula() - 1));
                        JOptionPane.showMessageDialog(null, "Asistencia registrada");
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Error en asignar asistencia " + e);
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAsignarAsistencia dialog = new DialogAsignarAsistencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Clase para cargar fondo
     */
    class FondoPanel extends JPanel {

        private Image image;

        /**
         * Metodo para pintar los graficos de los grafos en la pantalla
         *
         * @param g
         */
        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("../img/fondoBlanco.jpg")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHorasMateria;
    private javax.swing.JTextField txtHorasAsistidas;
    // End of variables declaration//GEN-END:variables
}
