/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.MatriculaController;
import controlador.listas.excepciones.ListaNullException;
import controlador.listas.excepciones.PosicionNoEncontradaException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Alumno;
import modelo.Asignatura;
import modelo.Cursa;
import modelo.Nota;
import modelo.Periodo;
import modelo.enums.Estado;
import vista.Tabla.ModeloTablaAsignatura;
import vista.Tabla.ModeloTablaMatriculas;
import vista.Utilidades.Utilidades;

/**
 *
 * @author TecnoeXtrem
 */
public class DialogMatriculas extends javax.swing.JDialog {
    
     private ModeloTablaAsignatura mta = new ModeloTablaAsignatura();
    private MatriculaController mC = new MatriculaController();
    private ModeloTablaMatriculas mtm = new ModeloTablaMatriculas();

    /**
     * Creates new form DialogoMatricula
     */
    public DialogMatriculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombos();
    }

    public void cargarCombos() {
        Utilidades.cargarEstados(cbxEstadoMatricula);
        Utilidades.cargarAlumnos(cbxAlumos, Utilidades.listarAlumnos());
        Utilidades.cargarPeriodos(cbxPeriodo, Utilidades.listarPeriodos());
    }

    public void cargatTablaAsignaturas() {
        mta.setListaAsignaturas(Utilidades.listarAsignaturas());
        tblPrincipal.setModel(mta);
        tblPrincipal.updateUI();
    }

    public void cargarTablaMatriculas(){
        mtm.setMatriculaList(Utilidades.listarMatriculas());
        tblPrincipal.setModel(mta);
        tblPrincipal.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        cbxPeriodo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        lblNumeroMaterias = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrar1 = new javax.swing.JButton();
        btnCrearPeriodo = new javax.swing.JButton();
        btnMostrar2 = new javax.swing.JButton();
        btnMostrarMatriculas = new javax.swing.JButton();
        lblNumeroMaterias1 = new javax.swing.JLabel();
        cbxEstadoMatricula = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cbxAlumos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoBlanco.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Matriculación");

        cbxPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPeriodoActionPerformed(evt);
            }
        });

        jLabel5.setText("Materias");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lblNumeroMaterias.setText("Materias");

        btnModificar.setText("Modificar");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        btnMostrar1.setText("+");
        btnMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar1ActionPerformed(evt);
            }
        });

        btnCrearPeriodo.setText("+");
        btnCrearPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPeriodoActionPerformed(evt);
            }
        });

        btnMostrar2.setText("-");

        btnMostrarMatriculas.setText("Mostrar matriculas");
        btnMostrarMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMatriculasActionPerformed(evt);
            }
        });

        lblNumeroMaterias1.setText("Estado:");

        cbxEstadoMatricula.setToolTipText("");

        tblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrincipal);

        jLabel3.setText("Periodo:");

        cbxAlumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlumosActionPerformed(evt);
            }
        });

        jLabel4.setText("Alumno: ");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addComponent(lblNumeroMaterias1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbxEstadoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblNumeroMaterias)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnMostrar)
                                            .addGap(6, 6, 6)
                                            .addComponent(btnMostrar1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnMostrar2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbxPeriodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbxAlumos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCrearPeriodo)))
                            .addGap(296, 296, 296))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(btnCrear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnModificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar)
                            .addGap(18, 18, 18)
                            .addComponent(btnMostrarMatriculas)
                            .addGap(81, 81, 81)))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearPeriodo)
                        .addComponent(cbxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbxAlumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(btnMostrar)
                        .addComponent(btnMostrar1)
                        .addComponent(btnMostrar2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblNumeroMaterias)
                    .addGap(18, 18, 18)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNumeroMaterias1)
                        .addComponent(cbxEstadoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(81, 81, 81)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrear)
                        .addComponent(btnModificar)
                        .addComponent(btnEliminar)
                        .addComponent(btnMostrarMatriculas))
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPeriodoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            // TODO add your handling code here:
            crearMatricula();
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(DialogMatriculas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaNullException ex) {
            Logger.getLogger(DialogMatriculas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        cargatTablaAsignaturas();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar1ActionPerformed
        // TODO add your handling code here:
        registrarAsignatura();
    }//GEN-LAST:event_btnMostrar1ActionPerformed

    private void btnCrearPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPeriodoActionPerformed
        // TODO add your handling code here:
        new DialogPeriodo(null, true).setVisible(true);
    }//GEN-LAST:event_btnCrearPeriodoActionPerformed

    private void btnMostrarMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMatriculasActionPerformed
        // TODO add your handling code here:
        cargarTablaMatriculas();
    }//GEN-LAST:event_btnMostrarMatriculasActionPerformed

    private void cbxAlumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlumosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAlumosActionPerformed
   
     public void crearMatricula() throws PosicionNoEncontradaException, ListaNullException {
        if (mC.getMatricula().getCursa().getSize() == 0) {
            JOptionPane.showMessageDialog(null, "Datos incompletos");
        } else {
            mC.getMatricula().setAlumno((Alumno) new Alumno());
            mC.getMatricula().setFechaEmision(new Date());
            mC.getMatricula().setPeriodo((Periodo) cbxPeriodo.getSelectedItem());
            mC.getMatricula().setPromedioGeneral((float)0.00);
            mC.getMatricula().setIdMatricula(Utilidades.listarMatriculas().getSize() + 1);
            Utilidades.guardarMatricula(mC.getMatricula());
            JOptionPane.showMessageDialog(null, "Se ha guardado matricula");
            for(int i = 0; i < mC.getMatricula().getCursa().getSize(); i++){
                mC.getMatricula().getCursa().obtener(i).setMatricula(mC.getMatricula());
                System.out.println(mC.getMatricula().getFechaEmision());
                Utilidades.guardarCursas(mC.getMatricula().getCursa().obtener(i));
            }
            
            
            mC.getMatricula().getCursa().vaciar();
        }

    }

    public void registrarAsignatura() {
        Asignatura asignatura = new Asignatura();
        Cursa cursa = new Cursa();
        if (tblPrincipal.getSelectedRow() >= 0) {
            int fila = tblPrincipal.getSelectedRow();
            asignatura = mta.leerAsignatura(fila);
            cursa.setAsignatura(asignatura);
            cursa.setEstadoAsignatura(Estado.REPROBADA);
            cursa.setHorasAsistidas(0);
            cursa.setMatricula(null);
            cursa.setNotaFinal(new Nota());
            cursa.setPorcentajeHorasAsistidas(0);

            mC.getMatricula().getCursa().insertar(cursa);
            lblNumeroMaterias.setText("Numero de materias: " + mC.getMatricula().getCursa().getSize());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMatriculas dialog = new DialogMatriculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrearPeriodo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrar1;
    private javax.swing.JButton btnMostrar2;
    private javax.swing.JButton btnMostrarMatriculas;
    private javax.swing.JComboBox<String> cbxAlumos;
    private javax.swing.JComboBox<String> cbxEstadoMatricula;
    private javax.swing.JComboBox<String> cbxPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroMaterias;
    private javax.swing.JLabel lblNumeroMaterias1;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JTable tblPrincipal;
    // End of variables declaration//GEN-END:variables
}
