/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CicloController;
import controlador.listas.excepciones.ListaNullException;
import controlador.listas.excepciones.ListaVaciaException;
import controlador.listas.excepciones.PosicionNoEncontradaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Asignatura;
import modelo.Ciclo;
import vista.Tabla.ModeloTablaAsignatura;
import vista.Tabla.ModeloTablaCiclo;
import vista.Utilidades.Utilidades;

/**
 *
 * @author Marylin
 */
public class DialogoCiclo extends javax.swing.JDialog {
    
    private CicloController cC = new CicloController();
    private ModeloTablaCiclo mtc = new ModeloTablaCiclo();
    private ModeloTablaAsignatura mta = new ModeloTablaAsignatura();
    private Integer indiceCiclo;

    /**
     * Creates new form DialogoCiclos
     */
    public DialogoCiclo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTablaCiclo();
    }
    
     public void cargarTablaAsignaturas() {
        mta.setListaAsignaturas(Utilidades.listarAsignaturas());
        tblAsignaturasCiclos.setModel(mta);
        tblAsignaturasCiclos.updateUI();
    }

    public void cargarTablaCiclo() {
        mtc.setListaCiclo(Utilidades.listarCiclos());
        tblAsignaturasCiclos.setModel(mtc);
        tblAsignaturasCiclos.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarAsignatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        txtNombreCiclo = new javax.swing.JTextField();
        btnCiclosDisponibles = new javax.swing.JButton();
        btnEliminarAsignatura = new javax.swing.JButton();
        btnModificarCiclo = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEliminarCiclo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsignaturasCiclos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAsignatura = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ciclo");

        btnAgregarAsignatura.setText("+");
        btnAgregarAsignatura.setEnabled(false);
        btnAgregarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAsignaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        btnSelecionar.setText("Mostrar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jLabel3.setText("Asignaturas:");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCiclosDisponibles.setText("Ciclos");
        btnCiclosDisponibles.setEnabled(false);
        btnCiclosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiclosDisponiblesActionPerformed(evt);
            }
        });

        btnEliminarAsignatura.setText("-");
        btnEliminarAsignatura.setEnabled(false);
        btnEliminarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAsignaturaActionPerformed(evt);
            }
        });

        btnModificarCiclo.setText("Modificar");
        btnModificarCiclo.setEnabled(false);
        btnModificarCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCicloActionPerformed(evt);
            }
        });

        btnMostrar.setText("Selecionar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnEliminarCiclo.setText("Eliminar");
        btnEliminarCiclo.setEnabled(false);
        btnEliminarCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCicloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCrear)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnSelecionar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAgregarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificarCiclo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarCiclo)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCiclosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarAsignatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(btnSelecionar)
                        .addComponent(btnEliminarAsignatura)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCiclosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnModificarCiclo)
                    .addComponent(btnMostrar)
                    .addComponent(btnEliminarCiclo))
                .addGap(16, 16, 16))
        );

        tblAsignaturasCiclos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAsignaturasCiclos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAsignaturasCiclosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAsignaturasCiclos);

        tblAsignatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAsignatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAsignaturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAsignatura);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAsignaturaActionPerformed
        try {
            // TODO add your handling code here:
            registrarAsignatura();
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaNullException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarAsignaturaActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        cargarTablaAsignaturas();
        btnCiclosDisponibles.setEnabled(true);
        btnAgregarAsignatura.setEnabled(true);
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        crearCiclo();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCiclosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiclosDisponiblesActionPerformed
        // TODO add your handling code here:
        indiceCiclo = null;
        btnEliminarAsignatura.setEnabled(false);
        txtNombreCiclo.setText("");
        cargarTablaCiclo();
    }//GEN-LAST:event_btnCiclosDisponiblesActionPerformed

    private void btnEliminarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAsignaturaActionPerformed
        eliminaAsignatura();
        try {
            cargarTablaAsignaturaCiclo();
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaNullException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarAsignaturaActionPerformed

    private void btnModificarCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCicloActionPerformed
        // TODO add your handling code here:
        if (indiceCiclo >= 0) {
            try {
                cC.setCiclo(cC.getCicloList().obtener(indiceCiclo));
                cC.getCiclo().setNombre(txtNombreCiclo.getText());
                Utilidades.modificarCiclo(cC.getCiclo(), indiceCiclo);
                cargarTablaAsignaturas();
                indiceCiclo = null;
            } catch (PosicionNoEncontradaException ex) {
                Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ListaNullException ex) {
                Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnModificarCicloActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        try {
            //             TODO add your handling code here
            cargarTablaAsignaturaCiclo();
            txtNombreCiclo.setText(cC.getCiclo().getNombre());
            btnModificarCiclo.setEnabled(true);
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaNullException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCicloActionPerformed
        try {
            // TODO add your handling code here:
            eliminarCiclo();
        } catch (ListaVaciaException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarCicloActionPerformed

    private void tblAsignaturasCiclosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsignaturasCiclosMouseClicked
        btnEliminarCiclo.setEnabled(true);
    }//GEN-LAST:event_tblAsignaturasCiclosMouseClicked

    private void tblAsignaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsignaturaMouseClicked
        // TODO add your handling code here:
        btnEliminarAsignatura.setEnabled(true);
    }//GEN-LAST:event_tblAsignaturaMouseClicked

    public void eliminaAsignatura(){
        try {
            // TODO add your handling code here:
            Utilidades.eliminarAsignaturaCiclo(indiceCiclo, tblAsignatura.getSelectedRow());
        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaVaciaException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaNullException ex) {
            Logger.getLogger(DialogoCiclo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void eliminarCiclo() throws ListaVaciaException, PosicionNoEncontradaException{
        if(indiceCiclo != null){
            Utilidades.eliminarCiclo(indiceCiclo);
            txtNombreCiclo.setText("");
            cargarTablaCiclo();
        }else{
            if(tblAsignaturasCiclos.getSelectedRow() >= 0 && mta.getListaAsignaturas() != cC.getCiclo().getAsignaturas()){
                Utilidades.eliminarCiclo(tblAsignaturasCiclos.getSelectedRow());
                cargarTablaCiclo();
            }else{
                JOptionPane.showMessageDialog(null, "Escoja un ciclo");
            }
        }
    }
    
     public void cargarTablaAsignaturaCiclo() throws PosicionNoEncontradaException, ListaNullException {
        int fila = tblAsignaturasCiclos.getSelectedRow();
        if (fila >= 0) {
            if (indiceCiclo == null) {
                indiceCiclo = tblAsignaturasCiclos.getSelectedRow();
            }
            cC.setCicloList(Utilidades.listarCiclos());
            cC.setCiclo(cC.getCicloList().obtener(indiceCiclo));

            mta.setListaAsignaturas(cC.getCiclo().getAsignaturas());
            tblAsignatura.setModel(mta);
            tblAsignatura.updateUI();
        }
    }

    public void crearCiclo() {
        if (txtNombreCiclo.getText().isEmpty() || cC.getAsignaturaList().getSize() == 0) {
            JOptionPane.showMessageDialog(null, "Datos incompletos");
        } else {
            cC.getCiclo().setNombre(txtNombreCiclo.getText());
            cC.getCiclo().setAsignaturas(cC.getAsignaturaList());
            cC.getCiclo().setId(Utilidades.listarCiclos().getSize() + 1);
            Utilidades.guardarCiclo(cC.getCiclo());
            JOptionPane.showMessageDialog(null, "Ciclo registrado");
            cC.getAsignaturaList().vaciar();

        }
    }
    
     public void registrarAsignatura() throws PosicionNoEncontradaException, ListaNullException {
        Asignatura asignatura = new Asignatura();
        if (tblAsignaturasCiclos.getSelectedRow() >= 0) {
            int fila = tblAsignaturasCiclos.getSelectedRow();
            asignatura = mta.leerAsignatura(fila);
            if (indiceCiclo != null) {
                cC.setCiclo(cC.getCicloList().obtener(indiceCiclo));
                cC.getCiclo().getAsignaturas().insertar(asignatura);
                Utilidades.modificarCiclo(cC.getCiclo(), indiceCiclo);
                cargarTablaAsignaturaCiclo();
            } else {
                cC.getAsignaturaList().insertar(asignatura);
            }
        }
    }

    public void modificarListaAsignaturas() throws PosicionNoEncontradaException, ListaNullException {
        int fila = tblAsignaturasCiclos.getSelectedRow();
        if (fila >= 0) {
            cC.setCiclo(cC.getCicloList().obtener(fila));

//            cC.getCiclo().setAsignaturas(asignaturas);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoCiclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoCiclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoCiclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoCiclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoCiclo dialog = new DialogoCiclo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAsignatura;
    private javax.swing.JButton btnCiclosDisponibles;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminarAsignatura;
    private javax.swing.JButton btnEliminarCiclo;
    private javax.swing.JButton btnModificarCiclo;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAsignatura;
    private javax.swing.JTable tblAsignaturasCiclos;
    private javax.swing.JTextField txtNombreCiclo;
    // End of variables declaration//GEN-END:variables
}
