/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.AlumnoController;
import controlador.AsignaturaController;
import controlador.CursaController;
import controlador.DocentesController;
import controlador.MatriculaController;
import controlador.listas.ListaEnlazada;
import controlador.listas.excepciones.ListaNullException;
import controlador.listas.excepciones.PosicionNoEncontradaException;
import java.awt.Graphics;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import modelo.Asignatura;
import modelo.Docente;
import modelo.Matricula;
import vista.Tabla.ModeloTablaAlumnoDocente;
import vista.Tabla.ModeloTablaCompanieroEstudiante;
import vista.Utilidades.Utilidades;

/**
 *
 * @author TecnoeXtrem
 */
public class FrmDocente extends javax.swing.JDialog {

    private FondoPanel fondo = new FondoPanel();
    private AsignaturaController asigC = new AsignaturaController();
    private DocentesController dC = new DocentesController();
    private MatriculaController mC = new MatriculaController();
    private AlumnoController alumControler = new AlumnoController();
    private ModeloTablaAlumnoDocente mtad = new ModeloTablaAlumnoDocente();
    private CursaController cursaControler = new CursaController();

    /**
     * Creates new form FrmDocente
     */
    public FrmDocente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setContentPane(fondo);
        initComponents();
    }

    public FrmDocente(java.awt.Frame parent, boolean modal, Docente docente) {
        super(parent, modal);
        this.setContentPane(fondo);
        dC.setDocente(docente);
        initComponents();
        cambiarLabels();
        cargarCombos();
        this.setLocationRelativeTo(this);
    }

    public void cambiarLabels() {
        lblNombreDocente.setText(dC.getDocente().getNombres() + " " + dC.getDocente().getApellidos());
    }

    public void cargarCombos() {
        asigC.setAsignatursList(obtenerAsignaturas());
        Utilidades.cargarAsignaturas(cbxAsignaturas, asigC.getAsignatursList());
    }

    public ListaEnlazada<Asignatura> obtenerAsignaturas() {
        asigC.setAsignatursList(Utilidades.listarAsignaturas());
        ListaEnlazada<Asignatura> asignaturaList = new ListaEnlazada<>();
        try {
            for (int i = 0; i < asigC.getAsignatursList().getSize(); i++) {
                if (asigC.getAsignatursList().obtener(i).getDocente().getIdDocente() == dC.getDocente().getIdDocente()) {
                    asignaturaList.insertar(asigC.getAsignatursList().obtener(i));
                }
            }
        } catch (Exception e) {
            System.out.println("Error en obtenerAsignaturas " + e);
        }
        return asignaturaList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreDocente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxAsignaturas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnVerPerfil = new javax.swing.JButton();
        btnCalificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombreDocente.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNombreDocente.setText("Nombre del docente");

        jLabel2.setText("Materia: ");

        cbxAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxAsignaturasMouseClicked(evt);
            }
        });
        cbxAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAsignaturasActionPerformed(evt);
            }
        });

        tblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrincipal);

        jButton1.setText("Perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cargar alumnos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnVerPerfil.setText("Ver perfil");
        btnVerPerfil.setEnabled(false);
        btnVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPerfilActionPerformed(evt);
            }
        });

        btnCalificar.setText("Calificar");
        btnCalificar.setEnabled(false);
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerPerfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCalificar)))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblNombreDocente))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(btnVerPerfil)
                    .addComponent(btnCalificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmPerfilDocente pD = new FrmPerfilDocente(null, true, dC.getDocente());
        this.setVisible(true);
        pD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAsignaturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAsignaturasActionPerformed

    private void cbxAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxAsignaturasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAsignaturasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cargarTablaEstudiantes();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPerfilActionPerformed
        // TODO add your handling code here:
        if (tblPrincipal.getSelectedRow() >= 0) {
            int indiceAlumno = tblPrincipal.getSelectedRow();
            try {
                alumControler.setAlumno(alumControler.getAlumnoList().obtener(tblPrincipal.getSelectedRow()));
                VistaPerfilEstudiante pE = new VistaPerfilEstudiante(null, true, alumControler.getAlumno(), dC.getDocente());
                this.setVisible(false);
                pE.setVisible(true);
                this.dispose();
            } catch (PosicionNoEncontradaException ex) {
                Logger.getLogger(FrmDocente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ListaNullException ex) {
                Logger.getLogger(FrmDocente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnVerPerfilActionPerformed

    private void tblPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrincipalMouseClicked
        // TODO add your handling code here:
        btnVerPerfil.setEnabled(true);
        btnCalificar.setEnabled(true);
    }//GEN-LAST:event_tblPrincipalMouseClicked

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        // TODO add your handling code here:
        if (tblPrincipal.getSelectedRow() >= 0) {
            try {
                alumControler.setAlumno(alumControler.getAlumnoList().obtener(tblPrincipal.getSelectedRow()));
                System.out.println("Cursa " + cursaControler.getCursaList().obtener(tblPrincipal.getSelectedRow()).getAsignatura());
                DialogCalificar dialogCalificar = new DialogCalificar(null, true, alumControler.getAlumno(), 
                        cursaControler.getCursaList().obtener(tblPrincipal.getSelectedRow()), dC.getDocente(),
                        mC.getMatriculaList());
                this.setVisible(false);
                dialogCalificar.setVisible(true);
                this.dispose();
            } catch (PosicionNoEncontradaException ex) {
                Logger.getLogger(FrmDocente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ListaNullException ex) {
                Logger.getLogger(FrmDocente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCalificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        DialogoAdmLogin diaLogin = new DialogoAdmLogin(null, true);
        this.setVisible(false);
        diaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void cargarTablaEstudiantes() {
        cargarInfoEstudiantes();
        mtad.setAlumnoList(alumControler.getAlumnoList());
//        cursaControler.calcularNotaFinal();
        mtad.setCursaList(cursaControler.getCursaList());
        alumControler.setAlumnoList(alumControler.getAlumnoList());
        tblPrincipal.setModel(mtad);
        tblPrincipal.updateUI();
    }

    public void cargarInfoEstudiantes() {
        mC.setMatriculaList(obtenerMatriculas());
        Asignatura a = (Asignatura) cbxAsignaturas.getSelectedItem();
        try {

            for (int i = 0; i < mC.getMatriculaList().getSize(); i++) {
                for (int j = 0; j < mC.getMatriculaList().obtener(i).getCursa().getSize(); j++) {
//                    System.out.println("FOR " + mC.getMatriculaList().obtener(i).getCursa().obtener(j).getAsignatura().getNombre());
                    if (a.getNombre().equals(mC.getMatriculaList().obtener(i).getCursa().obtener(j).getAsignatura().getNombre())) {
                        alumControler.getAlumnoList().insertar(mC.getMatriculaList().obtener(i).getAlumno());
                        cursaControler.getCursaList().insertar(mC.getMatriculaList().obtener(i).getCursa().obtener(j));
                        System.out.println("Estudiante " + j);
                    }
                }
            }
            System.out.println("mC " + alumControler.getAlumnoList().getSize());

        } catch (PosicionNoEncontradaException ex) {
            Logger.getLogger(FrmEstidiante.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ListaNullException ex) {
            Logger.getLogger(FrmEstidiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ListaEnlazada<Matricula> obtenerMatriculas() {
        mC.setMatriculaList(Utilidades.listarMatriculas());
        ListaEnlazada<Matricula> matriculaList = new ListaEnlazada<>();
        Matricula matricula = null;
        try {
            for (int i = 0; i < mC.getMatriculaList().getSize(); i++) {
                matricula = null;
                for (int j = 0; j < mC.getMatriculaList().getSize(); j++) {
                    if (mC.getMatriculaList().obtener(i).getAlumno().getId() == mC.getMatriculaList().obtener(j).getAlumno().getId()) {
                        if (matricula == null) {
                            matricula = new Matricula();
                            matricula = mC.getMatriculaList().obtener(j);
                        } else if (mC.getMatriculaList().obtener(j).getFechaEmision().after(matricula.getFechaEmision())) {
                            matricula = mC.getMatriculaList().obtener(j);
                        }
                    }
                }
                matriculaList.insertar(matricula);
            }
            for (int i = 0; i < matriculaList.getSize(); i++) {
                for (int j = 0; j < matriculaList.getSize(); j++) {
                    if (matriculaList.obtener(i).getAlumno().getId() == matriculaList.obtener(j).getAlumno().getId() && i != j) {
                        matriculaList.eliminar(j);
                    }
                }

            }
        } catch (Exception e) {
            System.out.println("Error en obtenerMatriculas " + e);
        }
        return matriculaList;
    }

    /**
     * @param args the command line arguments
     */
    class FondoPanel extends JPanel {

        private Image image;

        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("../img/fondoBlanco.jpg")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDocente dialog = new FrmDocente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerPerfil;
    private javax.swing.JComboBox<String> cbxAsignaturas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreDocente;
    private javax.swing.JTable tblPrincipal;
    // End of variables declaration//GEN-END:variables
}
