/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author DEEPIN
 */
public class FrmPersona extends javax.swing.JDialog {

    
    /**
     * Creates new form FrmPersona
     */
    public FrmPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        cargarCombos();
//        limpiar();
        setLocationRelativeTo(this);
    }
    
//    private void cargarTabla(){
//        mtp.setLista(personaDao.listar());
//        jTable1.setModel(mtp);
//        jTable1.updateUI();
//    }

//    private void cargarCombos() {
//        Utilidades.cargarTipoIndentificacion(cbxidentificacion);
//    }
//    
//    private void limpiar (){
//        cargarCombos();
//        cargarTabla();
//        txtApellidos.setText("");
//        txtcedula.setText("");
//        txtcorreo.setText("");
//        txtdireccion.setText("");
//        txtNombres.setText("");
//        personaDao.setPersona(null);
//    }

//    private void guardar() {
//        if (txtcedula.getText().isEmpty() || txtApellidos.getText().isEmpty()
//                || txtcorreo.getText().isEmpty() || txtdireccion.getText().isEmpty()
//                || txtNombres.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Ingrese los datos", "Error", JOptionPane.ERROR_MESSAGE);
//        } else {
//            Boolean verificar = false;
//            if (cbxidentificacion.getSelectedItem().toString().equalsIgnoreCase("PASAPORTE")) {
//                verificar = true;
//            } else if (!(cbxidentificacion.getSelectedItem().toString().equalsIgnoreCase("PASAPORTE")) &&
//                    controlador.utiles.Utilidades.validadorDeCedula(txtcedula.getText())) {
//                verificar = true;
//            } else {
//                verificar = false;
//                JOptionPane.showMessageDialog(null, "Cedula no valida", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//            if (verificar) {
//                //save
//                personaDao.getPersona().setApellidos(txtApellidos.getText());
//                personaDao.getPersona().setNombres(txtNombres.getText());
//                personaDao.getPersona().setCorreo(txtcorreo.getText());
//                personaDao.getPersona().setDireccion(txtdireccion.getText());
//                personaDao.getPersona().setId_rol(4);
//                personaDao.getPersona().setIndetifiacion(txtcedula.getText());
//                personaDao.getPersona().setTipoIdentificacion(Utilidades.obtenerTipoIdentificacion(cbxidentificacion));
//                try {
//                    if(personaDao.guardar()) {
//                        limpiar();
//                       JOptionPane.showMessageDialog(null, "Se ha registraso", "Exitosamente", JOptionPane.INFORMATION_MESSAGE); 
//                    }
//                    
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error desconocido", JOptionPane.ERROR_MESSAGE);
//                }
//                
//            }
//        }
//    }
    
    private void eliminar() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxidentificacion = new javax.swing.JComboBox<>();
        txtcedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbxtrol = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador Persona");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos"));
        jPanel1.setLayout(null);

        jLabel1.setText("Tipo Identificacion:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 120, 16);

        jLabel2.setText("Identificacion:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 40, 90, 16);

        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 70, 16);

        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 90, 50, 16);

        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 140, 60, 16);

        jLabel6.setText("Direccion:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 140, 80, 16);

        cbxidentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxidentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxidentificacionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxidentificacion);
        cbxidentificacion.setBounds(180, 40, 140, 22);
        jPanel1.add(txtcedula);
        txtcedula.setBounds(500, 40, 150, 22);
        jPanel1.add(txtNombres);
        txtNombres.setBounds(500, 90, 150, 22);
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(500, 140, 150, 22);
        jPanel1.add(txtcorreo);
        txtcorreo.setBounds(180, 140, 140, 22);
        jPanel1.add(txtApellidos);
        txtApellidos.setBounds(180, 90, 140, 22);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(180, 190, 79, 25);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 190, 79, 25);

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 190, 90, 25);

        jLabel7.setText("Rol:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 190, 23, 16);

        cbxtrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxtrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtrolActionPerformed(evt);
            }
        });
        jPanel1.add(cbxtrol);
        cbxtrol.setBounds(530, 190, 100, 22);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Listado"));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 680, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxidentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxidentificacionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        eliminar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modificar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxtrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtrolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPersona dialog = new FrmPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxidentificacion;
    private javax.swing.JComboBox<String> cbxtrol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    // End of variables declaration//GEN-END:variables

    private void modificar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
